image: java:8-jdk

stages:
  - build
  - test
  - deploy-test

before_script:
  - echo "CI started..." 
  - export GRADLE_USER_HOME=`pwd`/.gradle
  
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  variables:
    GIT_STRATEGY: clone
  script: 
    - chmod +x ./gradlew
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
  tags:
    - ugrad
  
test:
  stage: test
  variables:
    GIT_STRATEGY: clone
  script:     
    -  chmod +x ./gradlew
    - ./gradlew check
  tags:
    - ugrad

deploy-test:
  stage: deploy-test
  variables:
    GIT_STRATEGY: clone
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_REPO || true
    - git push -f heroku HEAD:master
  only:
     - develop
  tags:
    - ugrad